"""Update focus session and distraction models

Revision ID: 8d8850cd16ff
Revises: 5204844e58dc
Create Date: 2025-12-30 12:00:22.751422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8d8850cd16ff'
down_revision: Union[str, None] = '5204844e58dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('distractions', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False))
    op.drop_column('distractions', 'distraction_type')
    op.drop_column('distractions', 'source_app')
    op.drop_column('distractions', 'url')
    op.drop_column('distractions', 'occurred_at')
    op.drop_column('distractions', 'destination_app')
    op.add_column('focus_sessions', sa.Column('start_time', sa.DateTime(), nullable=True))
    op.add_column('focus_sessions', sa.Column('end_time', sa.DateTime(), nullable=True))
    op.add_column('focus_sessions', sa.Column('actual_duration', sa.Integer(), nullable=True))
    op.add_column('focus_sessions', sa.Column('completed', sa.Boolean(), nullable=False))
    op.drop_column('focus_sessions', 'started_at')
    op.drop_column('focus_sessions', 'break_duration_minutes')
    op.drop_column('focus_sessions', 'is_completed')
    op.drop_column('focus_sessions', 'ended_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('focus_sessions', sa.Column('ended_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('focus_sessions', sa.Column('is_completed', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('focus_sessions', sa.Column('break_duration_minutes', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('focus_sessions', sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('focus_sessions', 'completed')
    op.drop_column('focus_sessions', 'actual_duration')
    op.drop_column('focus_sessions', 'end_time')
    op.drop_column('focus_sessions', 'start_time')
    op.add_column('distractions', sa.Column('destination_app', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('distractions', sa.Column('occurred_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('distractions', sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('distractions', sa.Column('source_app', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('distractions', sa.Column('distraction_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('distractions', 'name')
    # ### end Alembic commands ###
